import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import * as XLSX from 'xlsx'

function formatDate(value) {
  const date = value?.toDate?.() || (value instanceof Date ? value : null)
  return date ? date.toLocaleDateString('en-IN') : 'Pending'
}

export function flattenOrderRows(orders) {
  return orders.flatMap((order) =>
    (order.items || []).map((item) => ({
      orderId: order.id,
      userId: order.userId || '',
      customerName: order.customerName || '',
      customerEmail: order.customerEmail || '',
      productName: item.name || '',
      productId: item.productCode || item.productId || '',
      quantity: Number(item.quantity || 0),
      price: Number(item.price || 0),
      total: Number(item.price || 0) * Number(item.quantity || 0),
      status: order.status || 'Pending',
      date: formatDate(order.createdAt),
    })),
  )
}

export function exportOrdersToExcel(orders) {
  const rows = flattenOrderRows(orders).map((row) => ({
    'Order ID': row.orderId,
    'User ID': row.userId,
    'Customer Name': row.customerName,
    'Customer Email': row.customerEmail,
    'Product Name': row.productName,
    'Product ID': row.productId,
    Quantity: row.quantity,
    Price: row.price,
    Total: row.total,
    Status: row.status,
    Date: row.date,
  }))

  const worksheet = XLSX.utils.json_to_sheet(rows)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Orders')
  XLSX.writeFile(workbook, 'alan-mens-wear-orders.xlsx')
}

export function exportOrdersToPdf(orders) {
  const rows = flattenOrderRows(orders)
  const totalRevenue = orders
    .filter((order) => order.status === 'Delivered')
    .reduce((total, order) => total + Number(order.totalAmount || 0), 0)
  const deliveredOrders = orders.filter((order) => order.status === 'Delivered').length
  const doc = new jsPDF({ orientation: 'landscape' })

  doc.setFillColor(16, 22, 32)
  doc.rect(0, 0, 297, 34, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('Alan Mens Wear', 14, 16)
  doc.setFontSize(10)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 14, 24)

  doc.setTextColor(16, 22, 32)
  doc.setFontSize(11)
  doc.text(`Orders: ${orders.length}`, 14, 44)
  doc.text(`Delivered: ${deliveredOrders}`, 52, 44)
  doc.text(`Total Revenue: Rs. ${totalRevenue.toLocaleString('en-IN')}`, 96, 44)

  autoTable(doc, {
    startY: 52,
    head: [['Order ID', 'Customer', 'Product', 'Amount', 'Status', 'Date']],
    body: rows.map((row) => [
      row.orderId.slice(0, 10),
      row.customerName,
      row.productName,
      `Rs. ${row.total.toLocaleString('en-IN')}`,
      row.status,
      row.date,
    ]),
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [16, 22, 32], textColor: [214, 178, 109] },
  })

  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(9)
  doc.setTextColor(89, 98, 114)
  doc.text('Generated by Alan Mens Wear Admin System', 14, pageHeight - 10)
  doc.save('alan-mens-wear-orders.pdf')
}
